Update postCSS and button style (#71)
* Switching toCSS and postCSS

Warning:
```
WARN  deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed in a future release. Use css.Sass instead.
WARN  deprecated: resources.PostCSS was deprecated in Hugo v0.128.0 and will be removed in a future release. Use css.PostCSS instead.
ERROR POSTCSS: failed to transform "/css/bundle.css" (text/css): Error: Cannot find module '@fullhuman/postcss-purgecss'
```

* Fix button dimensions

* Version information